FROM node:25.6.0-slim

RUN apt update && apt install -y procps curl && rm -rf /var/lib/apt/lists/*

WORKDIR /home/node/app

COPY package*.json ./

RUN mkdir -p node_modules && chown -R node:node /home/node/app

USER node

CMD ["tail", "-f", "/dev/null"]
